# permissions for end users to edit eqemuconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: eqemuconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: eqemu-kube
    app.kubernetes.io/part-of: eqemu-kube
    app.kubernetes.io/managed-by: kustomize
  name: eqemuconfig-editor-role
rules:
- apiGroups:
  - eqemu.eqemu-kube
  resources:
  - eqemuconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eqemu.eqemu-kube
  resources:
  - eqemuconfigs/status
  verbs:
  - get
