---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - eqemu.eqemu-kube
  resources:
  - eqemuconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eqemu.eqemu-kube
  resources:
  - eqemuconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - eqemu.eqemu-kube
  resources:
  - eqemuconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - eqemu.eqemu-kube
  resources:
  - zones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eqemu.eqemu-kube
  resources:
  - zones/finalizers
  verbs:
  - update
- apiGroups:
  - eqemu.eqemu-kube
  resources:
  - zones/status
  verbs:
  - get
  - patch
  - update
