apiVersion: eqemu.eqemu-kube/v1
kind: Zone
metadata:
  labels:
    app.kubernetes.io/name: zone
    app.kubernetes.io/instance: zone-sample
    app.kubernetes.io/part-of: eqemu-kube
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: eqemu-kube
  name: zone-sample
spec:
  # TODO(user): Add fields here
